### ISSUE TITLE
Use builder pattern

### ISSUE THREAD

**Issue by TarekkMA** [mrudultora/Colorpicker#3]
Currently, there is a lot of code duplication between `ColorPickerBottomSheetDialog` and `ColorPickerDialog`.

So I suggest that you refactor the library to utilize a builder pattern to build a dialog/sheet/popup with all the user configuration/default configurations.

I think doing that will result in a far more clean code.

**Comment by mrudultora** [comment]
@TarekkMA I agree that both classes have some similar code. But for bottom sheets complete layout is used (buttons etc. Are fetched from layout). But in dialogs I just set the content view. So some part of code looks duplicate but in actual it's not.

**Comment by TarekkMA** [comment]
I meant to use the builder pattern for configuration instead of setters. When you build the builder use configuration as finls inside the dialog.

I will see if i can make a PR to demonstrate what I meant
