### ISSUE TITLE
ok and cancel button are very small 

### ISSUE THREAD

**Issue by Akshay0701** [mrudultora/Colorpicker#9]
**Describe the bug**
ok and cancel button are very small 

**Screenshots**
![1b97dd53-20fd-4836-bc8e-2854ff638434](https://user-images.githubusercontent.com/52353967/122559905-8cefe500-d05d-11eb-8fe3-c47dc29387d1.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mrudultora** [comment]
Hi @Akshay0701, it's a strange issue. I hope this may work.
```
colorPickerDialog.show();
colorPickerDialog.getPositiveButton().setTextSize(TypedValue.COMPLEX_UNIT_SP,14f);
colorPickerDialog.getNegativeButton().setTextSize(TypedValue.COMPLEX_UNIT_SP,14f);
```

**Comment by Akshay0701** [comment]
thanks!

**Comment by Akshay0701** [comment]
one more question when i tried to set default color like this 

> .setColors(Color.red); 

application crashed

**Comment by mrudultora** [comment]
Wait, for setting default color you have to use `.setDefaultColor(Color.RED)` and for setting the list of colors please use it as below.
```
        // Option 1: Pass the resource id of array
	.setColors(R.array.array_colors)
	
	//Option 2: Pass the arraylist of HEX colors in String format.
	.setColors(new ArrayList<>(Arrays.asList("#95afc0", "#ff7979", "#ffbe76", "#7ed6df", "#badc58")))
	
	// Option 3: Pass any number of colors in int format.
	.setColors(Color.RED, Color.BLUE, Color.GREEN, Color.BLACK, Color.YELLOW,Color.CYAN,Color.MAGENTA)
	
	// Option 4: Use Predefined 15 colors array.
	.setColors()
	.setOnDirectSelectColorListener(new OnDirectSelectColorListener() {
                    @Override
                    public void onDirectColorSelected(int color, int position) {
                        
                    }
                })
	.show();
```

**Comment by Akshay0701** [comment]
Thanks You so much
